import streamlit as st

st.set_page_config(page_title="Statistical Methodology", layout="wide")

st.title("🧮 Statistical Methodology")
st.markdown("""
This page outlines the specific statistical frameworks, data preprocessing steps, and algorithms used behind the scenes in the **Kinematics Longitudinal Analyzer**. 

Formal statistical testing is powered by **Pingouin** (an open-source statistical package built on Pandas and SciPy) and **Statsmodels** (for advanced mixed-effects modeling).
""")

st.markdown("---")

st.header("1. Data Preprocessing & Aggregation")
st.markdown("""
Before any statistical test is performed, the raw data undergoes automated cleaning and structuring to meet the rigorous assumptions of longitudinal statistics:

* **Trial Aggregation:** If a single subject has multiple trials recorded for the exact same Timepoint, the script automatically aggregates these by calculating the **Arithmetic Mean**. This prevents pseudo-replication in the statistical models.
* **Variance Metrics:** Error bars on the longitudinal plots are generated by calculating the **Standard Error of the Mean (SEM)**. 
""")

st.header("2. Automated Smart Stats Engine (Longitudinal Analysis)")
st.markdown("""
Biological datasets are frequently messy—data can be highly skewed, and subjects may miss timepoints due to disease progression or mortality. To prevent inaccurate p-values and "Survivor Bias", this application utilizes an automated **decision-tree statistical engine**. 

Before running tests, the engine checks two primary assumptions:
1. **Normality:** Evaluated automatically using the **Shapiro-Wilk test** for each group.
2. **Design Balance:** The dataset is scanned to check if any subjects are missing timepoints.

Based on these assumptions, the engine routes your data through one of three rigorous statistical pipelines:

### Pipeline A: 2-Way Mixed-Design ANOVA
**Trigger:** Data is Normally Distributed AND Perfectly Balanced (No missing timepoints).
* **Framework:** A standard Split-Plot ANOVA evaluating the Within-Subject factor (`Timepoint_Weeks`) and Between-Subject factor (`Group`).
* **Sphericity Correction:** Mauchly's test for sphericity is computed internally. If violated, the model automatically applies the **Greenhouse-Geisser correction** (`p-GG-corr`) to adjust the degrees of freedom and prevent Type I errors.
* **Post-Hocs:** Pairwise tests for simple main effects across the interaction term, evaluating differences at each timepoint. 

### Pipeline B: Linear Mixed-Effects Models (LMM)
**Trigger:** Data is Normally Distributed BUT contains Missing Timepoints.
* **Framework:** Standard ANOVAs use "listwise deletion", meaning a mouse missing Week 52 will have its Week 4, 12, and 24 data completely deleted. This severely underpowers the study and creates **Survivor Bias**. Instead, the script upgrades to a **Linear Mixed-Effects Model (LMM)** using Restricted Maximum Likelihood (REML). 
* **Advantage:** LMMs handle unbalanced longitudinal data gracefully, utilizing all available data points for every subject to estimate the true trajectory of the disease without dropping sick animals.
* **Post-Hocs:** Because standard repeated-measures post-hocs force listwise deletion, the engine slices the data cross-sectionally. It runs independent **Welch's T-Tests** between groups at each available timepoint.

### Pipeline C: Non-Parametric Analysis
**Trigger:** Data Violates Normality (Highly Skewed).
* **Framework:** Kinematic variables (like standard deviation of step length, or extreme dragging events) often severely violate normality. Running an ANOVA on skewed data produces invalid p-values.
* **Post-Hocs:** The engine safely falls back to robust, rank-based **Mann-Whitney U tests** to evaluate group differences cross-sectionally at each timepoint.
""")

st.header("3. Multiple Comparisons Correction & Plotting")
st.markdown("""
If you evaluate groups across 8 different timepoints, you are running 8 separate statistical tests. By pure mathematical probability, running multiple tests increases the risk of a False Positive (Type I error).

To strictly control the Family-Wise Error Rate (FWER), **all post-hoc p-values generated by pipelines A, B, and C are penalized and corrected using the Holm-Bonferroni Step-Down Method** (`padjust='holm'`).

The resulting rigorous, corrected p-values are mapped to standard scientific asterisks and floated dynamically above the highest data point (Mean + SEM) at each timepoint on your plots:
* `***` : p < 0.001
* `**` : p < 0.01
* `*` : p < 0.05
* `ns` : Not Significant (p >= 0.05)
""")

st.header("4. Radar Plot Normalization (Tab 6)")
st.markdown("""
When generating multivariate radar plots, combining different metrics (like angles in degrees and distances in meters) skews the visualization. To fix this, the script applies **Maximum-Abs Normalization** (Proportional Scaling):
* Each individual measurement group is divided by the highest aggregate mean found for that specific metric across all groups. 
* This mathematically constraints all data between 0.0 and 1.0, preserving the exact geometric ratios between your experimental groups without letting large-number variables dominate the shape of the plot.
""")

st.markdown("---")

st.info("""
💡 **Tip for Manuscript Writing:** Because the application dynamically adjusts to your data, you should check the "Model Assumptions" expander on Tab 4 before writing your methods section. You can use these templates:

* **If Pipeline A triggered:** *"Longitudinal progression was analyzed using a Two-Way Mixed-Design ANOVA with Greenhouse-Geisser sphericity corrections where applicable. Post-hoc simple main effects were evaluated using pairwise t-tests adjusted via the Holm-Bonferroni method."*
* **If Pipeline B triggered:** *"To account for missing data points and prevent survivor bias, longitudinal progression was analyzed using a Linear Mixed-Effects Model (LMM). Post-hoc cross-sectional simple main effects were evaluated using Welch's independent t-tests, adjusted for multiple comparisons via the Holm-Bonferroni method."*
* **If Pipeline C triggered:** *"Due to violations of normality, longitudinal differences were evaluated cross-sectionally at each timepoint using non-parametric Mann-Whitney U tests, with p-values adjusted for multiple comparisons using the Holm-Bonferroni step-down method."*
""")