import streamlit as st

st.set_page_config(page_title="Statistical Methodology", layout="wide")

st.title("🧮 Statistical Methodology")
st.markdown("""
This page outlines the specific statistical frameworks, data preprocessing steps, and algorithms used behind the scenes in the **Kinematics Longitudinal Analyzer**. 

Formal statistical testing is powered by **Pingouin** (an open-source statistical package built on Pandas and SciPy) and **Statsmodels** (for advanced mixed-effects modeling and estimating equations).
""")

st.markdown("---")

st.header("1. Data Preprocessing & Aggregation")
st.markdown("""
Before any statistical test is performed, the raw data undergoes automated cleaning and structuring to meet the rigorous assumptions of statistical modeling:

* **Trial Aggregation:** If a single subject has multiple trials recorded for the exact same Timepoint, the script automatically aggregates these by calculating the **Arithmetic Mean**. This prevents pseudo-replication in the statistical models.
* **Variance Metrics:** Error bars on the plots are generated by calculating the **Standard Error of the Mean (SEM)**. 
""")

st.header("2. Automated Smart Stats Engine")
st.markdown("""
Biological datasets are frequently messy—data can be highly skewed, and subjects may miss timepoints due to disease progression or mortality. To prevent inaccurate p-values, "Survivor Bias", or the misapplication of tests, this application utilizes an automated **decision-tree statistical engine**. 

### The Cross-Sectional Engine (1 Timepoint Selected)
If you select exactly **one timepoint** to analyze, the longitudinal models are bypassed. The engine evaluates the specific timepoint cross-sectionally:
* **Normality Check:** An Ordinary Least Squares (OLS) model is fit, and normality is checked on the residuals.
* **Parametric:** If normal, it utilizes **Welch's Independent T-Test**, which is highly robust to unequal sample sizes and unequal variances.
* **Non-Parametric:** If normality is violated, it safely falls back to the robust rank-based **Mann-Whitney U** test.

### The Longitudinal Engine (2+ Timepoints Selected)
When tracking progression over time, the engine must account for repeated measures. Before running longitudinal tests, the engine checks two primary assumptions:
1. **Residual Normality:** Evaluated automatically by fitting a baseline OLS model and running the **Shapiro-Wilk test on the model residuals**. Testing the residuals (rather than raw pooled data) is the statistical "Gold Standard" for longitudinal data, preventing the natural spread of time from artificially failing the normality test.
2. **Design Balance:** The dataset is scanned to check if any subjects are missing timepoints.

Based on these assumptions, the engine routes your data through one of three rigorous longitudinal pipelines:

#### Pipeline A: 2-Way Mixed-Design ANOVA
**Trigger:** Residuals are Normally Distributed AND Perfectly Balanced (No missing timepoints).
* **Framework:** A standard Split-Plot ANOVA evaluating the Within-Subject factor (`Timepoint_Weeks`) and Between-Subject factor (`Group`).
* **Sphericity Correction:** Mauchly's test for sphericity is computed internally. If violated, the model automatically applies the **Greenhouse-Geisser correction** (`p-GG-corr`) to adjust the degrees of freedom and prevent Type I errors.
* **Post-Hocs:** Pairwise independent t-tests for simple main effects, evaluating differences at each timepoint. 

#### Pipeline B: Linear Mixed-Effects Models (LMM)
**Trigger:** Residuals are Normally Distributed BUT the data contains Missing Timepoints.
* **Framework:** Standard ANOVAs use "listwise deletion", meaning a mouse missing Week 52 will have its earlier data completely deleted. This severely underpowers the study and creates **Survivor Bias**. Instead, the script upgrades to a **Linear Mixed-Effects Model (LMM)**. 
* **Advantage:** LMMs handle unbalanced longitudinal data gracefully, utilizing all available data points for every subject to estimate the true trajectory of the disease without dropping sick animals.
* **Post-Hocs:** Evaluated cross-sectionally using independent **Welch's T-Tests** between groups at each available timepoint to account for unequal variances.

#### Pipeline C: Generalized Estimating Equations (GEE)
**Trigger:** Residuals Violate Normality (Highly Skewed).
* **Framework:** Running an ANOVA or standard LMM on severely skewed data produces invalid p-values. The engine upgrades to a robust **Generalized Estimating Equations (GEE)** model with an exchangeable correlation structure. 
* **Advantage:** GEE utilizes robust "Sandwich" variance estimators. This means it safely handles non-normal, skewed data while perfectly preserving the repeated-measures structure of your longitudinal study.
* **Post-Hocs:** Pairwise contrasts are derived mathematically directly from the GEE model coefficients using Wald tests.
""")

st.header("3. Multiple Comparisons Correction & Plotting")
st.markdown("""
If you evaluate groups across 8 different timepoints, you are running 8 separate statistical tests. By pure mathematical probability, running multiple tests inflates the risk of a False Positive (Type I error).

To strictly control the False Discovery Rate (FDR), **all post-hoc p-values generated by the longitudinal pipelines are penalized and corrected using the Holm-Bonferroni Step-Down Method** (`padjust='holm'`). The Holm method is statistically more powerful than the traditional Sidak/Bonferroni methods while maintaining the exact same strict 5% error threshold.

The resulting rigorous, corrected p-values are mapped to standard scientific asterisks and floated dynamically above the highest data point (Mean + SEM) at each timepoint on your plots:
* `***` : p < 0.001
* `**` : p < 0.01
* `*` : p < 0.05
* `ns` : Not Significant (p >= 0.05)
""")

st.header("4. Radar Plot Normalization (Tab 6)")
st.markdown("""
When generating multivariate radar plots, combining different metrics (like angles in degrees and distances in meters) skews the visualization. To fix this, the script applies **Maximum-Abs Normalization** (Proportional Scaling):
* Each individual measurement group is divided by the highest aggregate mean found for that specific metric across all groups. 
* This mathematically constraints all data between 0.0 and 1.0, preserving the exact geometric ratios between your experimental groups without letting large-number variables dominate the shape of the plot.
""")

st.markdown("---")

st.info("""
💡 **Tip for Manuscript Writing:** Because the application dynamically routes data to the most appropriate mathematical model, you should check the "Model Assumptions & Pipeline Selection" announcer on Tab 4 before writing your methods section. You can adapt these templates for your papers:

* **Cross-Sectional (1 Timepoint):** *"Cross-sectional group differences were evaluated using Welch's independent t-tests (for normally distributed data) or Mann-Whitney U tests (for non-normal distributions), following residual normality assessment via the Shapiro-Wilk test."*
* **Pipeline A (ANOVA):** *"Longitudinal progression was analyzed using a Two-Way Mixed-Design ANOVA, with residual normality confirmed via the Shapiro-Wilk test. Greenhouse-Geisser sphericity corrections were applied where applicable. Post-hoc simple main effects were evaluated using pairwise t-tests adjusted for multiple comparisons via the Holm-Bonferroni method."*
* **Pipeline B (LMM):** *"To account for missing data points and prevent survivor bias, longitudinal progression was analyzed using a Linear Mixed-Effects Model (LMM). Residual normality was confirmed via the Shapiro-Wilk test. Post-hoc cross-sectional simple main effects were evaluated using Welch's independent t-tests, adjusted for multiple comparisons via the Holm-Bonferroni method."*
* **Pipeline C (GEE):** *"Due to violations of residual normality, longitudinal progression was analyzed using Generalized Estimating Equations (GEE) with an exchangeable working correlation structure and robust standard errors. Pairwise simple main effects were extracted via model contrasts and adjusted for multiple comparisons using the Holm-Bonferroni method."*
""")