import streamlit as st

st.set_page_config(page_title="Statistical Methodology", layout="wide")

st.title("🧮 Statistical Methodology")
st.markdown("""
This page outlines the specific statistical frameworks, data preprocessing steps, and algorithms used behind the scenes in the **Kinematics Longitudinal Analyzer**. 

All formal statistical testing is powered by **Pingouin**, an open-source statistical package written in Python, built on top of Pandas and SciPy.
""")

st.markdown("---")

st.header("1. Data Preprocessing & Descriptive Statistics")
st.markdown("""
Before any statistical test is performed, the raw data undergoes automated cleaning and structuring to meet the rigorous assumptions of repeated-measures statistics:

* **Trial Aggregation:** If a single subject has multiple trials recorded for the exact same Timepoint, the script automatically aggregates these by calculating the **Arithmetic Mean**. 
* **Variance Metrics:** Error bars on the longitudinal plots are generated by calculating the **Standard Error of the Mean (SEM)**. Tab 5 diagnostics calculate the **Standard Deviation (SD)** to check for zero-variance groups.
* **Complete Case Analysis (Listwise Deletion):** Repeated measures analyses mathematically require a balanced design. If a subject is missing data for *even one* of the selected timepoints, that subject is dropped from the formal ANOVA analysis to preserve matrix symmetry.
""")

st.header("2. Formal Analysis (Tab 5: Two-Way Mixed ANOVA)")
st.markdown("""
To determine how kinematics metrics evolve over time between different experimental groups, the application utilizes a **Two-Way Mixed-Design ANOVA** (also known as a Split-Plot ANOVA).

* **Within-Subject Factor:** `Timepoint_Weeks` (Repeated measures across time).
* **Between-Subject Factor:** `Group` (Independent experimental cohorts).
* **Sphericity Correction:** By default, Pingouin computes Mauchly's test for sphericity under the hood. If the assumption of sphericity is violated, it automatically applies the **Greenhouse-Geisser correction** (indicated by `p-GG-corr` in your results table) to adjust the degrees of freedom and prevent Type I errors.

**Post-Hoc Multiple Comparisons:**
If the ANOVA indicates significant main effects or interactions, the script computes multiple comparisons to pinpoint exactly *where* those differences lie using **Pairwise Tests for Simple Main Effects**.
* It isolates the **Interaction Effect (`Timepoint_Weeks * Group`)** to compare the groups directly at every single timepoint using independent tests.
* **P-Value Adjustment:** To control for the Family-Wise Error Rate (FWER) and prevent false positives from multiple testing, p-values are rigorously corrected using the **Holm-Bonferroni Step-Down Method** (`padjust='holm'`).
""")

st.header("3. Longitudinal Plotting Significance (Tab 4)")
st.markdown("""
When the user toggles **"Show statistical significance (p-values) at each timepoint"** on the longitudinal plots, the script attempts a dynamic, two-tier statistical approach:

#### **Tier 1: Holm-Bonferroni Corrected Pairwise T-Tests**
The script first attempts to extract the exact same rigorous simple main effects used in Tab 5. It identifies complete-case subjects and runs **Pairwise T-Tests** across the interaction term, adjusting the final p-values using the **Holm-Bonferroni** correction. If successful, it plots these highly robust p-values.

#### **Tier 2: Welch's Two-Sample T-Test (Fallback)**
In longitudinal animal studies, data is frequently lost over time. If Tier 1 fails because there is too much missing data to form a complete repeated-measures dataset, the script activates a smart fallback mechanism:
* It isolates each timepoint individually.
* It performs a **Welch's Independent Two-Sample T-Test** between the two groups at that specific week. 
* *Why Welch's?* Unlike a standard Student's t-test, Welch's t-test does not assume equal population variances (heteroscedasticity) between your groups, making it much safer and more reliable for real-world biological data.
* *Note:* Because these are calculated independently per timepoint as a fallback visual aid, these specific p-values are uncorrected. 

#### **Significance Markers**
The resulting p-values are mapped to standard scientific asterisks and floated dynamically above the highest data point (Mean + SEM) at each timepoint:
* `***` : p < 0.001
* `**` : p < 0.01
* `*` : p < 0.05
* `ns` : Not Significant (p >= 0.05)
""")

st.header("4. Radar Plot Normalization (Tab 6)")
st.markdown("""
When generating multivariate radar plots, combining different metrics (like angles in degrees and distances in meters) skews the visualization. To fix this, the script applies **Maximum-Abs Normalization** (Proportional Scaling):
* Each individual measurement group is divided by the highest aggregate mean found for that specific metric across all groups. 
* This mathematically constraints all data between 0.0 and 1.0, preserving the exact geometric ratios between your experimental groups without letting large-number variables dominate the plot.
""")

st.markdown("---")

st.info("💡 **Tip for Manuscript Writing:** When citing the methods used in this app, you can state: *'Statistical analyses were performed using Python (Pingouin statistical package). Longitudinal progression was analyzed using a Two-Way Mixed-Design ANOVA with Greenhouse-Geisser sphericity corrections where applicable. Post-hoc simple main effects were evaluated using pairwise Welch's independent t-tests, adjusted for multiple comparisons via the Holm-Bonferroni method.'*")